apiVersion: v1
name: Health
version: 1.0.0
description: Health Helm chart
keywords:
  - lewisleteladoc  
home: https://github.com/lewisleteladoc/health/
appVersion: 1.0.0
# engine: gotpl
type: application
kubeVersion: ">=1.19.0-0"
sources:
   - https://github.com/lewisleteladoc/health/
maintainers:
  - name: Lewis Le
    email: haile819@gmail.com
    url: https://github.com/lewisleteladoc

dependencies:
  - name: servicebase
    repository: "@helm-charts"
    version: 1.1.0
    condition: global.servicebase.enabled
  - name: ingress
    repository: "@helm-charts"
    version: 1.1.0
    condition: global.ingress.enabled
  - name: job
    repository: "@helm-charts"
    version: 1.1.0
    condition: global.job.enabled
  - name: cronjob
    repository: "@helm-charts"
    version: 1.1.0
    condition: global.cronjob.enabled
  - name: secretsmanager
    repository: "@helm-charts"
    version: 1.2.4
    condition: global.secretsmanager.enabled
